### ISSUE TITLE
joint_script.sh does not support relative paths

### ISSUE THREAD

**Issue by tompollard** [mmcdermott/MEDS_transforms#27]
Minor thing, but it looks like `joint_script.sh` doesn't support relative paths (unless I'm doing something wrong). 

In the following command, I'm trying to point `MIMICIV_RAW_DIR` and `MIMICIV_PREMEDS_DIR` to `./MEDS_polars_functions/data`, but the script fails with a "different anchors" error:

```
./MIMIC-IV_Example/joint_script.sh data data/output_premeds data/output_meds 1
```

Error:

```
Running pre-MEDS conversion.
2024-07-01 12:26:37.242 | INFO     | __main__:main:102 - No function needed for hosp/poe: Symlinking /Users/tompollard/projects/MEDS_polars_functions/data/hosp/poe.csv.gz to /Users/tompollard/projects/MEDS_polars_functions/data/output_premeds/hosp/poe.csv.gz
Error executing job with overrides: ['raw_cohort_dir=data', 'output_dir=data/output_premeds']
Traceback (most recent call last):
  File "/Users/tompollard/projects/MEDS_polars_functions/./MIMIC-IV_Example/pre_MEDS.py", line 106, in main
    relative_in_fp = in_fp.relative_to(out_fp.resolve().parent, walk_up=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 686, in relative_to
    raise ValueError(f"{str(self)!r} and {str(other)!r} have different anchors")
ValueError: 'data/hosp/poe.csv.gz' and '/Users/tompollard/projects/MEDS_polars_functions/data/output_premeds/hosp' have different anchors
```

Easily addressed by specifying absolute paths, but making a note in case we want to fix this later.

**Comment by mmcdermott** [comment]
This script will be removed in favor of a better solution, and when #189 is merged that will close this issue.
